name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Ruby をセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Jekyll をビルド
        run: |
          bundle install
          bundle exec jekyll build

      - name: GitHub Pages にデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
